Sc2/item name strings
Ziktofel/Archipelago pull request #69
Opened 2023-10-12 08:07 UTC by MatthewMarinets

## What is this fixing or adding?
Created ItemNames.py, which is the ultimate source of truth on item names, assigning each of them to a variable. This improves speed and accuracy while coding, taking advantage of the IDE's intellisense and spellchecking:
![image](https://github.com/Ziktofel/Archipelago/assets/31861583/787b8432-55d0-416a-a1ac-10c7267902a2)

It also allows static analyzers like mypy to find issues with misspelled or undefined items.

Converting everything and running mypy exposed a few bugs, which were fixed (line numbers are pre-my changes):
* Items.py: 487: "Psi Disruptor" instead of "Psi Disupter"
* Items.py: 575: "Progressive Terran Starship Upgrade" instead of "Progressive Terran Ship Upgrade"
* LogicMixin.py: 154: "Psi Disruptor" instead of "Psi Disrupter"
* LogicMixin.py: 136: incorrect parens around `self._sc2wol_has_air_anti_air(multiworld, player) or self.has_any({'Battlecruiser', 'Valkyrie'}), player`
* PoolFilter.py: ~330: upgrade names changed
* LogicMixin.py: `_sc2wol_defense_rating()` was annotated to return bool, really returns int

## How was this tested?
I generated and hosted locally a few worlds. Things generated properly. This will probably take playing some games through to see things out.

## If this makes graphical changes, please attach screenshots.
Not user-facing, I just think the vscode scroll preview of ItemNames.py looks cool:
![image](https://github.com/Ziktofel/Archipelago/assets/31861583/d3154f17-5f77-4a9d-96aa-002dfbbfcdd8)

2023-10-12 08:41 UTC, MatthewMarinets commented on worlds/sc2/PoolFilter.py
> +UPGRADABLE_ITEMS = {item.parent_item for item in get_full_item_list().values() if item.parent_item}
I breakpointed in, and this set is equivalent to the old list (same length and contents). This object is only used with the `in` operator, so there's no need to keep it a list. It's more expensive, but this comprehension is only done once and is more future-proof as new upgrades are added.

I'm tempted to say this and the three sets below should probably live in another file; possibly a new one with item descriptions once those are added.

2023-10-12 08:47 UTC, MatthewMarinets commented
It's possible to give a similar treatment to item IDs, and key all future data off of item ID rather than item name. I think `int`s hash faster than `str` so there may be a minuscule performance improvement, but this is Python and I'm not sure it's worth it.

!Warning, opinions ahead!:
This opens the door to a very SQL-like table way of representing our data. We toss all the item data in a giant table; data associated with more than one item can live in a separate table and essentially use the item name (or item ID) as a foreign key into our main table. Python `dict`s can let us build indices into tables based on the key we use for the table. Not sure how much people think in relational / normalized database schemas, though. I personally find it easier to reason about than OOP as all the data is independently visible and you can separate out configuration from mutable data from functions.

2023-10-12 12:06 UTC, Ziktofel requested changes

2023-10-12 12:06 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +
Global to this file: These names are constants. Shouldn't be the names all uppercase (`BUNKER`)?

2023-10-12 12:06 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +
BTW can you apply some safeguard that these names can't be overwritten (they should be a real string constants)

2023-10-12 12:06 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +Kerrigan_Levels_70 = "70 Kerrigan Levels"
Sort these in a numeric order (1 - 70)

2023-10-13 01:02 UTC, MatthewMarinets commented on worlds/sc2/ItemNames.py
> +
re: uppercase, I'd generally prefer to keep things mostly lowercase just because I find it much easier to read and to type. It is technically what's requested by pep8, so if there's insistence on doing it I can. The execution on that would also be a pain. I'd either have to manually do a "rename instances" operation in my IDE on every variable individually, or write a script to automatically rewrite every variable here and every instance of `ItemNames.([\w_]+)` in the code.

re: defending against modification, while it is possible, it's hardly recommended. See [this Stack Overflow question](https://stackoverflow.com/questions/17242804/python-should-i-use-a-constant-or-a-property) for an example -- I can make all of these variables into properties that only define the getter and not the setter. This should cause errors if anyone tries to assign, at the cost of making this code less readable, and turning every access of one of these strings into a function call.

The docs for `@property`: https://docs.python.org/3/library/functions.html#property. They're intended for use on class members, so I'm not sure if they work at module level. I don't see why they wouldn't, and if they don't, it's simple to just wrap all these variables in a `class ItemNames:`

2023-10-13 01:23 UTC, MatthewMarinets commented on worlds/sc2/ItemNames.py
> +
A bit of testing with `@property` doesn't fill me with hope. The following example code:
```Python
class ItemNames:
    my_name = property(lambda x: 'my_name')
    @property
    def my_second_var(self): return 'my_second_var'
my_third_name = property(lambda x: 'my_third_name')

print(ItemNames.my_name)
print(ItemNames.my_second_var)
print(ItemNames().my_name)
print(ItemNames().my_second_var)
print(my_third_name)
ItemNames().my_name = "hello, world"
```
Produced the following output, before throwing AttributeError on `ItemNames().my_name = "hello, world"
```
<property object at 0x000001AAC7A61530>
<property object at 0x000001AAC7A61580>
my_name
my_second_var
<property object at 0x000001AAC7A61620>
```
So it would be possible to use properties by putting all the item names in a class and instantiating it once, then importing that instance everywhere we want names. Module-level properties don't work, and accessing the properties through the class doesn't work. I think this is more trouble than it's worth.

A unit test approach doesn't really make sense either; we either depend on the test somewhere in core that checks we don't change item names after we've submitted them, or we make our own unit tests that just duplicates this file and checks these values against duplicated values. At the end of the day I'm most agreement with this answer to the above-posted SO question:

>  Or you can accept that any protection you put in place can be side-stepped by someone who really wants to, then just re-quote whoever said that stuff about consenting adults and go with the very sensible notion that variables in `ALL_CAPS` are properly respected by enough developers that you just shouldn't worry about enforcing your notion of constant.

And ask that variables in `ItemNames` have a similar respect as `ALL_CAPS`. Who goes around changing variables in other modules without checking what they do first, anyways?

2023-10-13 11:26 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +
What about using: https://docs.python.org/3/library/enum.html#enum.StrEnum

2023-10-13 11:53 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +
and another thing - it's easy to mix `ItemName.Foo = "bar"` instead of proper `ItemName.Foo == "bar"`

Just wrapping into a StrEnum should get rid of these issues

2023-10-13 11:54 UTC, Ziktofel commented on worlds/sc2/ItemNames.py
> +
I'd use the `ALL_CAPS` to be more clear. Missions use enums and they are `ALL_CAPS`

2023-10-13 18:07 UTC, MatthewMarinets commented on worlds/sc2/ItemNames.py
> +
The issue with `StrEnum` is that it's new in version 3.11, and Archipelago supports down to 3.8. While that's old, I don't think anyone is suggesting we drop 3.10 support regardless.

Will go the `ALL_CAPS` route, will try updating the PR at lunch (in a couple hours), or after work in the evening (many hours)

2023-10-14 06:16 UTC, MatthewMarinets commented on worlds/sc2/ItemNames.py
> +
Upper-cased the variable names, vscode now shows all the variable typehints as `Literal["string contents"]` or `LiteralString`, so I'm much more positive on it now.

2023-10-14 08:49 UTC, merged